# Numpy Tutorial

## Simple Numpy example

In [5]:
import numpy as np

# list of values e.g temperature in celcius
cvalues = [25.3, 24.8, 26.9, 23.9]
print(cvalues)

[25.3, 24.8, 26.9, 23.9]


In [6]:
# transform list to one-dimensional numpy-array
C = np.array(cvalues)
print(C)

[ 25.3  24.8  26.9  23.9]


In [7]:
# turn values into farenheit using numpy
print(C * 9 / 5 + 32)

[ 77.54  76.64  80.42  75.02]


In [ ]:
# vs normal python
fvalues = [x*9/5 + 32 for x in cvalues]
print(fvalues)

## Creation of evenly spaced values

### arange

In [10]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [12]:
# vs range
x = range(1, 10)
print(x)

range(1, 10)


In [13]:
print(list(x))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [15]:
x = np.arange(10.4)
print(x)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [16]:
x = np.arange(0.5, 10.4, 0.8)
print(x)

[  0.5   1.3   2.1   2.9   3.7   4.5   5.3   6.1   6.9   7.7   8.5   9.3
  10.1]


In [17]:
x = np.arange(0.5, 10.4, 0.8, int)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


### linspace

In [18]:
# 50 values between 1 and 10
print(np.linspace(1, 10))

[  1.           1.18367347   1.36734694   1.55102041   1.73469388
   1.91836735   2.10204082   2.28571429   2.46938776   2.65306122
   2.83673469   3.02040816   3.20408163   3.3877551    3.57142857
   3.75510204   3.93877551   4.12244898   4.30612245   4.48979592
   4.67346939   4.85714286   5.04081633   5.2244898    5.40816327
   5.59183673   5.7755102    5.95918367   6.14285714   6.32653061
   6.51020408   6.69387755   6.87755102   7.06122449   7.24489796
   7.42857143   7.6122449    7.79591837   7.97959184   8.16326531
   8.34693878   8.53061224   8.71428571   8.89795918   9.08163265
   9.26530612   9.44897959   9.63265306   9.81632653  10.        ]


In [19]:
# 7 values between 1 and 10
print(np.linspace(1, 10, 7))

[  1.    2.5   4.    5.5   7.    8.5  10. ]


In [21]:
# excluding endpoint
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571]


In [22]:
# returning the spacing between values
samples, spacing = np.linspace(1, 10, retstep=True)
print(spacing)

0.183673469388


In [24]:
samples, spacing = np.linspace(1, 10, 20, retstep=True)
print(spacing)

0.473684210526


## Time comparison between Python lists and numpy Arrays

In [29]:
import time

size_of_vec = 1000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

t1 = pure_python_version()
t2 = numpy_version()

In [30]:
print('python: {}'.format(t1))
print('numpy: {}'.format(t2))
print('numpy is {} faster than python'.format(t1/t2))

python: 0.0007901191711425781
numpy: 7.581710815429688e-05
numpy is 10.421383647798741 faster than python


### Measuring time with timeit module

In [31]:
from timeit import Timer

size_of_vec = 1000

def pure_python_version():
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])

def numpy_version():
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y

# timer_obj = Timer('x = x + 1', 'x = 0')
timer_obj1 = Timer('pure_python_version()', 'from __main__ import pure_python_version')
timer_obj2 = Timer('numpy_version()', 'from __main__ import numpy_version')
print(timer_obj1.timeit(10))
print(timer_obj2.timeit(10))

0.005276263982523233
0.0005645760102197528


## Creating arrays

### Zero-dimensional arrays in numpy

In [32]:
x = np.array(42)
print(x)
print('the type of x: ', type(x))
print('the dimension of x: ', np.ndim(x))

42
the type of x:  <class 'numpy.ndarray'>
the dimension of x:  0


### One-dimensional arrays

In [33]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
V = np.array([3.4, 6.9, 99.8, 12.8])
print('F: ', F)
print('V: ', V)
print('type of F: ', F.dtype)
print('type of V: ', V.dtype)
print('dimensions of F: ', np.ndim(F))
print('dimensions of V: ', np.ndim(V))

F:  [ 1  1  2  3  5  8 13 21]
V:  [  3.4   6.9  99.8  12.8]
type of F:  int64
type of V:  float64
dimensions of F:  1
dimensions of V:  1


### Two and Multidimensional arrays

In [34]:
A = np.array([
    [3.4, 8.7, 9.9],
    [1.1, -7.8, -0.7],
    [4.1, 12.3, 4.8],
])

print(A)
print(A.ndim)

[[  3.4   8.7   9.9]
 [  1.1  -7.8  -0.7]
 [  4.1  12.3   4.8]]
2


## Shape of an array

In [35]:
x = np.array([ [67, 63, 87],
               [77, 69, 59],
               [85, 87, 99],
               [79, 72, 71],
               [63, 89, 93],
               [68, 92, 78]])
print(np.shape(x))

(6, 3)


In [36]:
print(x.shape)

(6, 3)


In [37]:
# changing shape
x.shape = (3, 6)
print(x)

[[67 63 87 77 69 59]
 [85 87 99 79 72 71]
 [63 89 93 68 92 78]]


In [38]:
# number of elements must correspond to the original array
x.shape = (4, 4)

ValueError: cannot reshape array of size 18 into shape (4,4)

In [39]:
# the shape of a scalar is a empty tuple
x = np.array(11)
print(np.shape(x))

()


In [40]:
B = np.array([ [[111, 112], [121, 122]],
               [[211, 212], [221, 222]],
               [[311, 312], [321, 322]] ])
print(B.shape)

(3, 2, 2)


## Indexing and slicing

In [41]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(F[0])

1


In [42]:
print(F[-1])

21


In [44]:
print(F[-2])

13


In [45]:
len(F)

8

In [46]:
F[-8]

1

In [47]:
F[-9]

IndexError: index -9 is out of bounds for axis 0 with size 8